apiVersion: v1
kind: Namespace
metadata:
  name: test-service-a-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a-sa
  namespace: test-service-a-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deploy
  namespace: test-service-a-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 1.0.0
  template:
    metadata:
      labels:
        app: service-a
        version: 1.0.0
    spec:
      serviceAccountName: service-a-sa
      containers:
      - name: service-a-co
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "while curl \"http://service-b.test-service-b-ns/thingies('1001')\" 1>&2; do sleep 1.0; done;"]